#!/usr/bin/env python3
"""
Weekly maintenance for the known-link-shorteners datasets.

Three phases, each independently switchable:

  1. Clean    -- concurrent HEAD (GET fallback) liveness check of every active
                 domain. Domains that return a confirmed 403/404 or fail DNS
                 resolution are quarantined into data/inactive.json. Everything
                 else is kept; ambiguous results are reported, never removed.
  2. Ingest   -- reads candidates.txt, normalises each line to a bare domain,
                 drops anything already known, and asks a local Ollama model
                 (auto-discovered via /api/tags) whether the domain is a
                 shortener / link-in-bio / redirector / tracker or an ordinary
                 site. Accepted candidates become schema-valid entries.
  3. Normalise-- merges, deduplicates (across all four data files), sorts by
                 domain and rewrites every file in the repo's canonical format,
                 plus the flat mirror shorteners.txt.

shorteners.txt is the flat, human-readable list of every active domain: it is
read at the start of a run (hand-added lines are adopted into the dataset) and
regenerated at the end. data/*.json remains the source of truth, so output
still conforms to schema/shortener.schema.json and schema/inactive.schema.json
and `python scripts/validate_data.py` / `npm run ci` both keep passing.

Usage:
  python3 scripts/maintain_shorteners.py                 # full run
  python3 scripts/maintain_shorteners.py --dry-run       # change nothing
  python3 scripts/maintain_shorteners.py --no-check      # ingest only
  python3 scripts/maintain_shorteners.py --no-ollama     # liveness only
  python3 scripts/maintain_shorteners.py --limit 50      # probe a sample
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
import threading
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass, asdict
from datetime import date, datetime, timezone
from pathlib import Path
from typing import Any, Iterable

import requests
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
DIST = ROOT / "dist"

ACTIVE_FILES = ["shorteners.json", "redirectors.json", "tracking.json"]
INACTIVE_FILE = "inactive.json"
# Flat, sorted mirror of every active domain. data/*.json stays authoritative;
# this file is what humans and downstream tools read, and hand-added lines in
# it are adopted back into the JSON on the next run.
FLAT_FILE = "shorteners.txt"
CANDIDATES_HEADER = [
    "# candidates.txt -- one domain or URL per line.",
    "# Appended to by the Obsidian template; drained by scripts/maintain_shorteners.py.",
    "# Lines starting with # are ignored.",
    "",
]
FLAT_HEADER = [
    "# known-link-shorteners -- flat list of every active domain.",
    "# Generated by scripts/maintain_shorteners.py; data/*.json is the source of truth.",
    "# Hand-added lines are adopted into data/shorteners.json on the next run.",
    "",
]
FILE_FOR_TYPE = {
    "shortener": "shorteners.json",
    "redirector": "redirectors.json",
    "tracking": "tracking.json",
}

# Only these three outcomes may ever be written to inactive.json -- enforced by
# schema/inactive.schema.json and scripts/validate_data.py, and matching
# scripts/probe_domains.py so the weekly and monthly runs cannot disagree.
QUARANTINE_STATUSES = {"403", "404", "dns_error"}
# Which of them actually trigger a quarantine. Note that a shortener whose root
# path serves no page answers 404 while working perfectly (1drv.ms, b23.tv), so
# a maintainer may prefer --quarantine-on dns.
QUARANTINE_ALIASES = {"dns": "dns_error", "dns_error": "dns_error", "403": "403", "404": "404"}

DOMAIN_RE = re.compile(
    r"^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?(\.[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?)*$"
)

# Measured on the full 1,533-domain list: a self-identifying agent string is
# answered with HTTP 429 by the CDNs most shorteners sit behind, turning ~22%
# of the list into unusable "review" results. A standard browser agent returns
# the real 301/302 for those same domains, so liveness data is only meaningful
# with one. Override with --user-agent.
USER_AGENT = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36"
)
DEFAULT_HEADERS = {
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.9",
}

DEFAULT_TIMEOUT = 6.0
DEFAULT_WORKERS = 24
# Ambiguous results are re-checked slowly: 32 parallel requests trip per-IP
# limits on the CDNs these domains share, and 71% of the 429s in a measured
# full run resolved to a normal 301/302 when re-checked at this concurrency.
DEFAULT_RETRY_WORKERS = 4
# A 429 means "come back later", so actually come back later. Sweeping the full
# list repeatedly in a short window gets the source IP throttled outright.
DEFAULT_RETRY_DELAY = 10.0
DEFAULT_OLLAMA_HOST = os.environ.get("OLLAMA_HOST") or "http://localhost:11434"
DEFAULT_OLLAMA_MODEL = os.environ.get("OLLAMA_MODEL") or None
# Nothing is hardcoded as a hard requirement: Ollama tags differ between
# machines, so we ask /api/tags what is actually installed and take the best
# match in this order, falling back to whatever is installed first.
MODEL_PREFERENCE = ["qwen2.5", "llama3.2", "mistral"]
# Embedding / vision-only models cannot answer a text classification prompt.
MODEL_EXCLUDE = ("embed", "bge-", "nomic-", "minilm", "clip", "moondream")
# Usable in a pinch, but a general instruct model classifies domains better.
MODEL_DEPRIORITISE = ("coder", "code", "vision", "-vl", "math", "guard")
DEFAULT_CONFIDENCE = 0.6
DEFAULT_MIN_PARAMS = 7.0
# Two independent models must agree before anything is written to the dataset.
DEFAULT_CONSENSUS = 2
# Discovery supplies provenance; 1 upstream list is enough to auto-accept, and a
# domain with none (e.g. hand-added) goes to the review queue instead.
DEFAULT_MIN_SOURCES = 1
DEFAULT_OLLAMA_WORKERS = 2
# Refuse to mass-quarantine: a DNS outage on the runner must not empty the list.
DEFAULT_MAX_QUARANTINE_PCT = 5.0
QUARANTINE_FLOOR = 10
# Distinct from argparse's exit 2, so CI can tell a tripped cap from a usage error.
EXIT_QUARANTINE_CAP = 3

DNS_MARKERS = (
    "nodename nor servname provided",
    "name or service not known",
    "nxdomain",
    "getaddrinfo failed",
    "temporary failure in name resolution",
)

CATEGORY_TO_TYPE = {
    "shortener": "shortener",
    "link_in_bio": "shortener",
    "redirector": "redirector",
    "tracking": "tracking",
}

CLASSIFIER_PROMPT = """You are classifying an internet domain for a public database of URL shorteners.

Domain: {domain}

Categories:
- "shortener": a URL shortening service that turns a long URL into a short one (bit.ly, tinyurl.com, t.co, is.gd).
- "link_in_bio": a link-in-bio / link hub service hosting a page of outbound links (linktr.ee, beacons.ai, bio.link).
- "redirector": a service whose purpose is to bounce a visitor to another site (l.facebook.com, out.reddit.com).
- "tracking": a click-tracking, affiliate or analytics redirect domain (doubleclick.net, go.redirectingat.com).
- "other": anything else -- news sites, shops, blogs, SaaS apps, CDNs, personal sites, or a domain you do not recognise.

Rules:
- If you are not confident the domain's PRIMARY purpose is one of the first four categories, answer "other".
- A short domain name is not on its own evidence of a shortener.
- Do not guess. Unknown means "other".

Reply with JSON only, no prose:
{{"category": "<one of: shortener, link_in_bio, redirector, tracking, other>", "confidence": <0.0-1.0>, "reason": "<max 15 words>"}}"""


# --------------------------------------------------------------------------- IO

def rel(path: Path) -> str:
    """Repo-relative path for display, tolerating paths outside the repo."""
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


def load_json(path: Path) -> list:
    if not path.exists():
        return []
    with path.open(encoding="utf-8") as f:
        return json.load(f)


def save_json(path: Path, data: Any) -> None:
    """Repo canonical format: 2-space indent, UTF-8 preserved, trailing newline."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write("\n")


def read_lines(path: Path) -> list[str]:
    if not path.exists():
        return []
    with path.open(encoding="utf-8") as f:
        return [line.strip() for line in f]


def write_lines(path: Path, header: list[str], lines: Iterable[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        for line in header:
            f.write(line + "\n")
        for line in lines:
            f.write(line + "\n")


# ------------------------------------------------------------------ normalising

def parse_candidate_line(line: str) -> tuple[str, list[str]] | None:
    """Split a candidates.txt line into (raw_domain, source_urls).

    Discovery writes provenance inline as `example.com  # src=https://a,https://b`
    so a queued domain carries the evidence that justified queueing it.
    """
    if not line or line.lstrip().startswith("#"):
        return None
    domain_part, _, comment = line.partition("#")
    domain_part = domain_part.strip()
    if not domain_part:
        return None
    sources: list[str] = []
    marker = comment.strip()
    if marker.startswith("src="):
        sources = [u.strip() for u in marker[4:].split(",") if u.strip().startswith(("http://", "https://"))]
    return domain_part, sources


def format_candidate_line(domain: str, sources: list[str]) -> str:
    return f"{domain}  # src={','.join(sources)}" if sources else domain


def normalise_domain(raw: str, strip_www: bool = True) -> str | None:
    """Turn a pasted URL or hostname into a bare, schema-valid domain.

    strip_www is off when re-reading our own canonical output: the dataset does
    contain www-prefixed entries (www.shrunken.com), and rewriting those on a
    round-trip would make the flat mirror non-idempotent.
    """
    value = raw.strip().strip('"\'<>,;')
    if not value or value.startswith("#"):
        return None
    value = re.sub(r"^[a-z][a-z0-9+.-]*://", "", value, flags=re.IGNORECASE)
    value = value.split("/")[0].split("?")[0].split("#")[0]
    value = value.split("@")[-1]          # strip user:pass@
    value = value.split(":")[0]           # strip :port
    value = value.strip().rstrip(".").lower()
    # No dataset entry is www-prefixed; www.nytimes.com and nytimes.com are the
    # same site, and candidates pasted from articles routinely carry the prefix.
    if strip_www and value.startswith("www.") and value.count(".") > 1:
        value = value[4:]
    if not value or "." not in value:
        return None
    if not value.isascii():
        try:
            value = value.encode("idna").decode("ascii")
        except (UnicodeError, ValueError):
            return None
    return value if DOMAIN_RE.match(value) else None


# ------------------------------------------------------------------ liveness

@dataclass
class CheckResult:
    domain: str
    origin: str
    verdict: str            # "alive" | "dead" | "review"
    status: int | str
    scheme: str
    method: str
    message: str | None = None


_local = threading.local()
_user_agent = USER_AGENT


def get_session() -> requests.Session:
    session = getattr(_local, "session", None)
    if session is None:
        session = requests.Session()
        session.headers.update({**DEFAULT_HEADERS, "User-Agent": _user_agent})
        # Our own scheme/method fallback is the retry strategy; only let
        # urllib3 retry the cheap connect-level failures.
        adapter = HTTPAdapter(
            pool_connections=16,
            pool_maxsize=16,
            max_retries=Retry(total=1, connect=1, read=0, status=0, backoff_factor=0.3),
        )
        session.mount("https://", adapter)
        session.mount("http://", adapter)
        _local.session = session
    return session


def _request(method: str, url: str, timeout: float) -> requests.Response:
    return get_session().request(
        method, url, timeout=timeout, allow_redirects=False, stream=(method == "GET")
    )


def check_domain(domain: str, origin: str, timeout: float) -> CheckResult:
    """HEAD first (cheap), GET as fallback and as confirmation of a 403/404."""
    last: CheckResult | None = None
    for scheme in ("https", "http"):
        url = f"{scheme}://{domain}/"
        try:
            resp = _request("HEAD", url, timeout)
            status, method = resp.status_code, "HEAD"

            # Plenty of hosts mishandle HEAD -- confirm anything that looks
            # negative with a real GET before acting on it.
            if status in (400, 403, 404, 405, 501) or status >= 500:
                confirmed = False
                try:
                    resp = _request("GET", url, timeout)
                    resp.close()
                    status, method = resp.status_code, "GET"
                    confirmed = True
                except requests.RequestException:
                    pass
                if status in (403, 404) and not confirmed:
                    # HEAD said 403/404 but the confirming GET never landed --
                    # that is single-method evidence, not proof the host is dead.
                    last = CheckResult(domain, origin, "review", status, scheme, "HEAD",
                                       "403/404 on HEAD, confirming GET failed")
                    continue

            if status in (403, 404):
                # Confirmed by GET (or HEAD-only if GET failed): quarantine.
                return CheckResult(domain, origin, "dead", str(status), scheme, method)
            if 200 <= status < 400:
                return CheckResult(domain, origin, "alive", status, scheme, method)
            last = CheckResult(
                domain, origin, "review", status, scheme, method, "unexpected status"
            )
        except requests.exceptions.SSLError as e:
            last = CheckResult(domain, origin, "review", "tls_error", scheme, "HEAD", str(e)[:200])
            continue  # retry over http://
        except requests.exceptions.Timeout:
            last = CheckResult(domain, origin, "review", "timeout", scheme, "HEAD", "timed out")
            continue
        except requests.exceptions.ConnectionError as e:
            err = str(e).lower()
            if any(marker in err for marker in DNS_MARKERS):
                # DNS is scheme independent -- no point trying http://.
                return CheckResult(domain, origin, "dead", "dns_error", scheme, "HEAD", err[:200])
            last = CheckResult(domain, origin, "review", "connect_error", scheme, "HEAD", str(e)[:200])
            continue
        except Exception as e:  # noqa: BLE001 - never let one domain kill the run
            last = CheckResult(domain, origin, "review", "error", scheme, "HEAD", str(e)[:200])
            continue
    return last or CheckResult(domain, origin, "review", "error", "https", "HEAD", "no result")


def run_liveness(targets: list[tuple[str, str]], workers: int, timeout: float) -> list[CheckResult]:
    results: list[CheckResult] = []
    if not targets:
        return results
    done = 0
    with ThreadPoolExecutor(max_workers=workers) as pool:
        futures = {pool.submit(check_domain, d, o, timeout): (d, o) for d, o in targets}
        for fut in as_completed(futures):
            domain, origin = futures[fut]
            try:
                results.append(fut.result())
            except Exception as e:  # noqa: BLE001
                results.append(
                    CheckResult(domain, origin, "review", "error", "", "", str(e)[:200])
                )
            done += 1
            if done % 100 == 0 or done == len(targets):
                print(f"  checked {done}/{len(targets)}", flush=True)
    return results


# -------------------------------------------------------------------- Ollama

def list_models(host: str) -> list[tuple[str, float]]:
    """Installed models as (name, parameter_count_in_billions)."""
    r = requests.get(f"{host}/api/tags", timeout=5)
    r.raise_for_status()
    out: list[tuple[str, float]] = []
    for m in r.json().get("models", []):
        name = m.get("name")
        if not name:
            continue
        raw = str((m.get("details") or {}).get("parameter_size") or "").strip().upper()
        try:
            params = float(raw.rstrip("B")) if raw.endswith("B") else 0.0
        except ValueError:
            params = 0.0
        out.append((name, params))
    return sorted(out)


def resolve_model(host: str, requested: str | None, min_params: float) -> str | None:
    """Pick an installed model. Never fail over a missing hardcoded tag.

    Order: explicit request -> a preferred family (qwen2.5, llama3.2, mistral)
    at or above min_params -> the largest general-purpose model at or above
    min_params -> a preferred family at any size -> the largest model installed.

    The size floor is not arbitrary: measured against a 10-domain set on this
    task, llama3.2:3b scored 6/10 and called zapier.com, notion.so and
    vercel.app shorteners, while llama3.1:8b and phi4 both scored 9/10. A
    false positive here writes a wrong entry into a public dataset.
    """
    try:
        installed = list_models(host)
    except Exception as e:  # noqa: BLE001
        print(f"  Ollama unreachable at {host} ({e}); skipping candidate triage.")
        return None

    if not installed:
        print(f"  Ollama at {host} has no models installed (try: ollama pull qwen2.5).")
        return None
    print("  installed models: " + ", ".join(f"{n} ({p:g}B)" if p else n for n, p in installed))

    def exact(name: str, want: str) -> bool:
        """qwen2.5-coder must NOT satisfy a preference for qwen2.5."""
        return name.lower() == want.lower() or name.split(":")[0].lower() == want.lower()

    if requested:
        for name, _ in installed:
            if exact(name, requested) or name.split(":")[0].lower().startswith(requested.lower()):
                return name
        print(f"  requested model {requested!r} is not installed; falling back to discovery.")

    usable = [(n, p) for n, p in installed if not any(x in n.lower() for x in MODEL_EXCLUDE)]
    general = [(n, p) for n, p in usable if not any(x in n.lower() for x in MODEL_DEPRIORITISE)]
    biggest = sorted(general or usable, key=lambda t: t[1], reverse=True)

    for want in MODEL_PREFERENCE:
        for name, params in general:
            if exact(name, want) and params >= min_params:
                return name
    for name, params in biggest:
        if params >= min_params:
            print(f"  no preferred family at >={min_params:g}B; using the largest installed ({name}, {params:g}B).")
            return name
    for want in MODEL_PREFERENCE:
        for name, _ in general:
            if exact(name, want):
                print(f"  nothing at >={min_params:g}B installed; falling back to {name} "
                      "-- review auto-ingested entries closely.")
                return name
    if biggest:
        name = biggest[0][0]
        print(f"  no preferred model installed; falling back to {name}.")
        return name
    return None


def select_models(host: str, requested: str | None, min_params: float, count: int) -> list[str]:
    """Pick up to `count` distinct models to vote on each candidate.

    One 7B-class model scores about 9/10 on this task; requiring two independent
    models to agree is what turns that into an auto-accept gate a public dataset
    can live with. Falls back to however many are installed.
    """
    chosen: list[str] = []
    first = resolve_model(host, requested, min_params)
    if not first:
        return []
    chosen.append(first)
    if count <= 1:
        return chosen
    try:
        installed = list_models(host)
    except Exception:  # noqa: BLE001
        return chosen
    usable = [
        (n, pr) for n, pr in installed
        if not any(x in n.lower() for x in MODEL_EXCLUDE)
        and not any(x in n.lower() for x in MODEL_DEPRIORITISE)
        and n not in chosen
    ]
    # Prefer other large models, and prefer a different family for independence.
    def family(name: str) -> str:
        return name.split(":")[0].split("-")[0].lower()

    usable.sort(key=lambda t: (family(t[0]) == family(first), -t[1]))
    for name, params in usable:
        if len(chosen) >= count:
            break
        if params >= min_params:
            chosen.append(name)
    return chosen


def classify_candidate(domain: str, host: str, model: str, timeout: float) -> dict[str, Any]:
    payload = {
        "model": model,
        "prompt": CLASSIFIER_PROMPT.format(domain=domain),
        "stream": False,
        "format": "json",
        "options": {"temperature": 0, "num_predict": 120},
    }
    try:
        r = requests.post(f"{host}/api/generate", json=payload, timeout=timeout)
        r.raise_for_status()
        raw = r.json().get("response", "")
    except Exception as e:  # noqa: BLE001
        return {"domain": domain, "category": "error", "confidence": 0.0, "reason": str(e)[:200]}

    try:
        parsed = json.loads(raw)
    except json.JSONDecodeError:
        match = re.search(r"\{.*\}", raw, re.DOTALL)
        if not match:
            return {"domain": domain, "category": "error", "confidence": 0.0,
                    "reason": f"unparseable response: {raw[:120]}"}
        try:
            parsed = json.loads(match.group(0))
        except json.JSONDecodeError:
            return {"domain": domain, "category": "error", "confidence": 0.0,
                    "reason": f"unparseable response: {raw[:120]}"}

    category = str(parsed.get("category", "other")).strip().lower().replace("-", "_").replace(" ", "_")
    if category not in CATEGORY_TO_TYPE and category != "other":
        category = "other"
    try:
        confidence = max(0.0, min(1.0, float(parsed.get("confidence", 0.0))))
    except (TypeError, ValueError):
        confidence = 0.0
    return {
        "domain": domain,
        "category": category,
        "confidence": confidence,
        "reason": str(parsed.get("reason", ""))[:200],
    }


def run_triage(domains: list[str], host: str, models: list[str], workers: int,
               timeout: float) -> dict[str, list[dict]]:
    """Every model votes on every domain. Returns {domain: [vote, ...]}."""
    jobs = [(d, m) for d in domains for m in models]
    votes: dict[str, list[dict]] = {d: [] for d in domains}
    with ThreadPoolExecutor(max_workers=workers) as pool:
        futures = {
            pool.submit(classify_candidate, d, host, m, timeout): (d, m) for d, m in jobs
        }
        for fut in as_completed(futures):
            domain, model = futures[fut]
            try:
                verdict = fut.result()
            except Exception as e:  # noqa: BLE001
                verdict = {"domain": domain, "category": "error", "confidence": 0.0,
                           "reason": str(e)[:200]}
            verdict["model"] = model
            votes[domain].append(verdict)
    for vs in votes.values():
        vs.sort(key=lambda v: v["model"])
    return votes


# --------------------------------------------------------------------- entries

def decide(domain: str, votes: list[dict], sources: list[str], min_confidence: float,
           min_sources: int) -> dict[str, Any]:
    """Turn per-model votes plus corroboration into accept / reject / review.

    A vote counts for a type only when the model is confident enough. Every
    model that answered must land on the same side, and an accepted domain also
    needs `min_sources` independent upstream lists behind it. Anything else is a
    human decision, not a silent write to a public dataset.
    """
    answered = [v for v in votes if v["category"] != "error"]
    errored = [v for v in votes if v["category"] == "error"]
    if not answered:
        return {"domain": domain, "outcome": "error", "reason": "no model answered",
                "votes": votes, "sources": sources, "type": None}

    buckets = []
    for v in answered:
        entry_type = CATEGORY_TO_TYPE.get(v["category"])
        buckets.append(entry_type if entry_type and v["confidence"] >= min_confidence else None)

    agreed = len(set(buckets)) == 1
    bucket = buckets[0] if agreed else None
    mean_conf = sum(v["confidence"] for v in answered) / len(answered)
    base = {"domain": domain, "votes": votes, "sources": sources,
            "models": [v["model"] for v in answered], "confidence": round(mean_conf, 3)}

    if not agreed:
        disagreement = ", ".join(f"{v['model']}={v['category']}" for v in answered)
        return {**base, "outcome": "review", "type": None,
                "reason": f"models disagree ({disagreement})"}
    if bucket is None:
        return {**base, "outcome": "reject", "type": None,
                "reason": "all models say this is not a shortener/redirector/tracker"}
    if len(sources) < min_sources:
        return {**base, "outcome": "review", "type": bucket,
                "reason": f"classified {bucket} but only {len(sources)} corroborating "
                          f"source(s), need {min_sources}"}
    if errored:
        return {**base, "outcome": "review", "type": bucket,
                "reason": f"{len(errored)} model(s) failed to answer"}
    return {**base, "outcome": "accept", "type": bucket,
            "reason": f"{len(answered)} model(s) agree on {bucket}"}


def make_entry(decision: dict, today: str) -> dict:
    """Build an entry that satisfies schema/shortener.schema.json exactly."""
    domain = decision["domain"]
    sources = decision["sources"]
    models = ", ".join(decision["models"])
    note = (
        f"Auto-ingested: {decision['reason']} (confidence {decision['confidence']:.2f}, "
        f"models: {models}). Pending human review."
    )
    return {
        "domain": domain,
        "type": decision["type"],
        "status": "active",
        "added_at": today,
        "source": "internal",
        # Real provenance when discovery supplied it, the domain itself otherwise.
        "evidence": sources[:5] or [f"https://{domain}/"],
        "notes": note[:500],
    }


def make_inactive_entry(result: CheckResult, original: dict, today: str) -> dict:
    entry = {
        "domain": result.domain,
        "origin": result.origin,
        "last_status": str(result.status),
        "last_checked_at": today,
    }
    for key in ("added_at", "source", "evidence"):
        value = original.get(key)
        if value:
            entry[key] = value
    notes = original.get("notes")
    if notes:
        entry["notes"] = str(notes)[:500]
    elif result.status == "dns_error":
        entry["notes"] = "DNS resolution failed (weekly maintenance)"
    else:
        entry["notes"] = f"HTTP {result.status} (weekly maintenance)"
    return entry


# ------------------------------------------------------------------------ main

def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--candidates", type=Path, default=ROOT / "candidates.txt")
    parser.add_argument("--flat", type=Path, default=ROOT / FLAT_FILE,
                        help=f"flat mirror of all active domains (default: {FLAT_FILE})")
    parser.add_argument("--no-flat", action="store_true", help="do not read or write the flat mirror")
    parser.add_argument("--rejected", type=Path, default=ROOT / "candidates.rejected.txt")
    parser.add_argument("--no-check", action="store_true", help="skip the liveness phase")
    parser.add_argument("--no-ollama", action="store_true", help="skip candidate triage")
    parser.add_argument("--dry-run", action="store_true", help="report only, write nothing")
    parser.add_argument("--workers", type=int, default=DEFAULT_WORKERS)
    parser.add_argument("--retry-workers", type=int, default=DEFAULT_RETRY_WORKERS,
                        help="concurrency for the second-chance pass (default: 4)")
    parser.add_argument("--retry-delay", type=float, default=DEFAULT_RETRY_DELAY,
                        help="seconds to wait before the second-chance pass (default: 10)")
    parser.add_argument("--retry-timeout", type=float, default=0,
                        help="timeout for the second-chance pass (default: same as --timeout)")
    parser.add_argument("--no-retry", action="store_true",
                        help="skip the slow re-check of ambiguous results")
    parser.add_argument("--timeout", type=float, default=DEFAULT_TIMEOUT)
    parser.add_argument("--limit", type=int, default=0, help="probe only the first N domains")
    parser.add_argument("--ollama-host", default=DEFAULT_OLLAMA_HOST,
                        help="Ollama base URL (env: OLLAMA_HOST)")
    parser.add_argument("--model", default=DEFAULT_OLLAMA_MODEL,
                        help="force a model (env: OLLAMA_MODEL); default is auto-discovery")
    parser.add_argument("--ollama-workers", type=int, default=DEFAULT_OLLAMA_WORKERS)
    parser.add_argument("--ollama-timeout", type=float, default=120.0)
    parser.add_argument("--min-confidence", type=float, default=DEFAULT_CONFIDENCE)
    parser.add_argument("--consensus", type=int, default=DEFAULT_CONSENSUS,
                        help="how many distinct models must agree before a candidate is "
                             f"auto-accepted (default: {DEFAULT_CONSENSUS})")
    parser.add_argument("--min-sources", type=int, default=DEFAULT_MIN_SOURCES,
                        help="corroborating upstream sources required for auto-accept "
                             f"(default: {DEFAULT_MIN_SOURCES}); others go to the review queue")
    parser.add_argument("--review", type=Path, default=ROOT / "candidates.review.txt",
                        help="queue of candidates needing a human decision")
    parser.add_argument("--no-candidate-probe", action="store_true",
                        help="do not liveness-check candidates before adding them")
    parser.add_argument("--min-params", type=float, default=DEFAULT_MIN_PARAMS,
                        help="prefer models with at least this many billion parameters "
                             f"(default: {DEFAULT_MIN_PARAMS:g}); small models misclassify")
    parser.add_argument("--max-quarantine-pct", type=float, default=DEFAULT_MAX_QUARANTINE_PCT)
    parser.add_argument("--quarantine-on", default="dns,403,404",
                        help="which outcomes quarantine a domain (default: dns,403,404; "
                             "use 'dns' to keep root-404 shorteners such as 1drv.ms)")
    parser.add_argument("--user-agent", default=USER_AGENT,
                        help="override the probe User-Agent")
    parser.add_argument("--report", type=Path, default=DIST / "maintenance-report.json")
    args = parser.parse_args()

    today = date.today().isoformat()
    host = args.ollama_host.rstrip("/")

    global _user_agent
    _user_agent = args.user_agent

    triggers = set()
    for token in args.quarantine_on.split(","):
        token = token.strip().lower()
        if not token:
            continue
        if token not in QUARANTINE_ALIASES:
            parser.error(f"--quarantine-on: unknown value {token!r} (choose from dns, 403, 404)")
        triggers.add(QUARANTINE_ALIASES[token])
    if not triggers and not args.no_check:
        parser.error("--quarantine-on is empty: nothing could ever be quarantined. "
                     "Use --no-check to skip the liveness phase deliberately.")

    active: dict[str, list[dict]] = {name: load_json(DATA / name) for name in ACTIVE_FILES}
    inactive: list[dict] = load_json(DATA / INACTIVE_FILE)
    known: set[str] = {e["domain"] for entries in active.values() for e in entries}
    known_inactive: set[str] = {e["domain"] for e in inactive}

    print(f"Loaded {len(known)} active domains, {len(known_inactive)} inactive.")

    # The flat mirror is regenerated from the JSON, so anything a maintainer
    # hand-added to it would be silently wiped. Adopt those lines instead.
    adopted: list[str] = []
    flat_conflicts: list[str] = []
    flat_aliases: list[str] = []
    if not args.no_flat and args.flat.exists():
        flat_domains = {
            d
            for d in (normalise_domain(ln, strip_www=False) for ln in read_lines(args.flat))
            if d
        }
        for domain in sorted(flat_domains - known):
            if domain in known_inactive:
                flat_conflicts.append(domain)
                continue
            # www.shrunken.com and shrunken.com are the same site: adopting the
            # other spelling would silently create a paired duplicate entry that
            # no validator can catch.
            alias = domain[4:] if domain.startswith("www.") else f"www.{domain}"
            if alias in known:
                flat_aliases.append(f"{domain} (already present as {alias})")
                continue
            if alias in known_inactive:
                flat_conflicts.append(domain)
                continue
            active["shorteners.json"].append({
                "domain": domain,
                "type": "shortener",
                "status": "active",
                "added_at": today,
                "source": "internal",
                "evidence": [f"https://{domain}/"],
                "notes": f"Adopted from {args.flat.name} (hand-added); pending human review.",
            })
            known.add(domain)
            adopted.append(domain)
        if adopted:
            print(f"Adopted {len(adopted)} hand-added domain(s) from {args.flat.name}.")
        if flat_conflicts:
            print(f"Ignored {len(flat_conflicts)} {args.flat.name} line(s) already quarantined in {INACTIVE_FILE}.")
        if flat_aliases:
            print(f"Ignored {len(flat_aliases)} {args.flat.name} line(s) duplicating an existing entry.")
    report_flat = {
        "adopted": adopted,
        "ignored_inactive": flat_conflicts,
        "ignored_alias": flat_aliases,
    }

    report: dict[str, Any] = {
        "run_at": datetime.now(timezone.utc).isoformat(),
        "date": today,
        "dry_run": args.dry_run,
    }

    # ---------------------------------------------------------- phase 1: clean
    quarantined: list[dict] = []
    check_results: list[CheckResult] = []
    quarantine_skipped = False

    if args.no_check:
        print("\n[1/3] Liveness check skipped (--no-check).")
    else:
        targets = [
            (e["domain"], e.get("type", "shortener"))
            for name in ACTIVE_FILES
            for e in active[name]
        ]
        targets.sort()
        if args.limit:
            targets = targets[: args.limit]
        print(f"\n[1/3] Liveness check: {len(targets)} domains, {args.workers} workers, {args.timeout}s timeout.")
        check_results = run_liveness(targets, args.workers, args.timeout)

        # Second chance: a 429 means "come back later", and a timeout under
        # load is not evidence of anything. Re-check slowly before reporting.
        retry_stats = {"attempted": 0, "recovered": 0}
        if not args.no_retry:
            retry_targets = [(r.domain, r.origin) for r in check_results if r.verdict == "review"]
            if retry_targets:
                retry_timeout = args.retry_timeout or args.timeout
                if args.retry_delay > 0:
                    print(f"  waiting {args.retry_delay:.0f}s before re-checking "
                          f"{len(retry_targets)} ambiguous result(s)")
                    time.sleep(args.retry_delay)
                print(f"  re-checking {len(retry_targets)} ambiguous result(s) at "
                      f"{args.retry_workers} workers, {retry_timeout}s timeout")
                retried = {
                    r.domain: r
                    for r in run_liveness(retry_targets, args.retry_workers, retry_timeout)
                }
                merged: list[CheckResult] = []
                for r in check_results:
                    replacement = retried.get(r.domain) if r.verdict == "review" else None
                    if replacement is None:
                        merged.append(r)
                        continue
                    if replacement.verdict != "review":
                        retry_stats["recovered"] += 1
                    merged.append(replacement)
                check_results = merged
                retry_stats["attempted"] = len(retry_targets)
                print(f"  recovered {retry_stats['recovered']}/{len(retry_targets)} on retry")

        # A "dead" outcome the maintainer has excluded is downgraded to review,
        # never silently dropped.
        for r in check_results:
            if r.verdict == "dead" and str(r.status) not in triggers:
                r.verdict = "review"
                r.message = f"{r.status} excluded by --quarantine-on"
        dead = [r for r in check_results if r.verdict == "dead" and str(r.status) in QUARANTINE_STATUSES]

        # Circuit breaker: a runner-side network failure must never be able to
        # delete a large slice of the dataset in one unattended commit.
        cap = max(QUARANTINE_FLOOR, int(len(check_results) * args.max_quarantine_pct / 100))
        if len(dead) > cap:
            quarantine_skipped = True
            print(
                f"  !! {len(dead)} domains look dead, above the safety cap of {cap} "
                f"({args.max_quarantine_pct}%). Refusing to quarantine; inspect the report.",
                file=sys.stderr,
            )
            # Downgrade rather than drop: these are precisely the domains the
            # warning tells a human to go and look at, so they must stay in the
            # review counts and in the workflow's review table.
            for r in dead:
                r.verdict = "review"
                r.message = f"{r.status}: suppressed by the {cap}-domain safety cap"
            dead = []

        alive_count = sum(1 for r in check_results if r.verdict == "alive")
        review = [r for r in check_results if r.verdict == "review"]

        by_domain = {e["domain"]: e for entries in active.values() for e in entries}
        dead_domains = {r.domain for r in dead}
        for r in dead:
            quarantined.append(make_inactive_entry(r, by_domain.get(r.domain, {}), today))
        if dead_domains:
            for name in ACTIVE_FILES:
                active[name] = [e for e in active[name] if e["domain"] not in dead_domains]

        print(
            f"  alive: {alive_count} | dead: {len(dead_domains)} | needs review: {len(review)}"
        )
        report["liveness"] = {
            "checked": len(check_results),
            "alive": alive_count,
            "quarantined": len(dead_domains),
            "review": len(review),
            "quarantine_cap": cap,
            "quarantine_on": sorted(triggers),
            "retry": retry_stats,
            "user_agent": args.user_agent,
            "quarantine_skipped": quarantine_skipped,
            "results": [asdict(r) for r in check_results],
        }

    # --------------------------------------------------------- phase 2: ingest
    accepted: list[dict] = []
    rejected: list[str] = []
    review_queue: list[tuple[str, list[str], str]] = []   # (domain, sources, reason)
    decisions: list[dict] = []
    models: list[str] = []

    raw_lines = read_lines(args.candidates)
    seen_candidates: set[str] = set()
    pending: dict[str, list[str]] = {}          # domain -> corroborating sources
    skipped_known: list[str] = []
    unparseable: list[str] = []

    for line in raw_lines:
        parsed = parse_candidate_line(line)
        if parsed is None:
            continue                            # blank or comment
        raw_domain, sources = parsed
        domain = normalise_domain(raw_domain)
        if domain is None:
            unparseable.append(line)
            continue
        if domain in seen_candidates:
            # Same domain queued twice: union the provenance rather than drop it.
            pending.setdefault(domain, [])
            pending[domain] = sorted(set(pending[domain]) | set(sources))
            continue
        seen_candidates.add(domain)
        alias = domain[4:] if domain.startswith("www.") else f"www.{domain}"
        if domain in known or domain in known_inactive or alias in known or alias in known_inactive:
            skipped_known.append(domain)
            continue
        pending[domain] = sorted(set(sources))

    pending_domains = sorted(pending)

    if args.no_ollama:
        print(f"\n[2/3] Candidate triage skipped (--no-ollama). {len(pending_domains)} candidate(s) left in place.")
    elif not args.candidates.exists():
        print(f"\n[2/3] No {args.candidates.name} found; nothing to ingest.")
    elif not pending_domains:
        print(f"\n[2/3] No new candidates ({len(skipped_known)} already known, {len(unparseable)} unparseable).")
    else:
        print(f"\n[2/3] Candidate triage: {len(pending_domains)} new domain(s) via Ollama at {host}.")
        models = select_models(host, args.model, args.min_params, args.consensus)
        if models:
            print(f"  voting models ({len(models)}): {', '.join(models)}")
            if len(models) < args.consensus:
                print(f"  only {len(models)} usable model(s) installed; "
                      f"consensus of {args.consensus} requested.")
            votes = run_triage(pending_domains, host, models, args.ollama_workers, args.ollama_timeout)

            # A candidate that does not resolve is not worth adding, whatever
            # the models think of the name.
            liveness: dict[str, CheckResult] = {}
            if not args.no_candidate_probe:
                print(f"  probing {len(pending_domains)} candidate(s) for liveness")
                liveness = {
                    r.domain: r
                    for r in run_liveness([(d, "shortener") for d in pending_domains],
                                          min(args.workers, 8), args.timeout)
                }

            for domain in pending_domains:
                sources = pending[domain]
                decision = decide(domain, votes[domain], sources,
                                  args.min_confidence, args.min_sources)
                probe = liveness.get(domain)
                if decision["outcome"] == "accept" and probe is not None:
                    if probe.verdict == "dead":
                        decision = {**decision, "outcome": "reject",
                                    "reason": f"classified {decision['type']} but the domain is "
                                              f"dead ({probe.status})"}
                    elif probe.verdict == "review":
                        decision = {**decision, "outcome": "review",
                                    "reason": f"classified {decision['type']} but liveness is "
                                              f"inconclusive ({probe.status})"}
                decision["liveness"] = str(probe.status) if probe else None
                decisions.append(decision)

                if decision["outcome"] == "accept":
                    entry = make_entry(decision, today)
                    accepted.append(entry)
                    active[FILE_FOR_TYPE[decision["type"]]].append(entry)
                    known.add(domain)
                elif decision["outcome"] == "reject":
                    rejected.append(domain)
                elif decision["outcome"] == "review":
                    review_queue.append((domain, sources, decision["reason"]))
                # "error" outcomes stay in candidates.txt and are retried next run

            for d in decisions:
                icon = {"accept": "+", "reject": "-", "review": "?", "error": "!"}[d["outcome"]]
                print(f"  {icon} {d['domain']}: {d['reason']}")
            print(f"  accepted: {len(accepted)} | rejected: {len(rejected)} | "
                  f"needs review: {len(review_queue)}")

    report["ingest"] = {
        "candidate_lines": len(raw_lines),
        "new_candidates": len(pending_domains),
        "already_known": len(skipped_known),
        "unparseable": unparseable,
        "models": models,
        "consensus_required": args.consensus,
        "min_sources": args.min_sources,
        "accepted": [e["domain"] for e in accepted],
        "rejected": rejected,
        "review_queue": [{"domain": d, "sources": src, "reason": why} for d, src, why in review_queue],
        "decisions": decisions,
    }

    # ------------------------------------------------- phase 3: dedupe and sort
    print("\n[3/3] Deduplicating and sorting.")
    seen_global: set[str] = set()
    duplicates: list[str] = []
    for name in ACTIVE_FILES:
        unique: list[dict] = []
        for entry in active[name]:
            domain = entry.get("domain")
            if not domain or domain in seen_global:
                duplicates.append(domain or "<missing>")
                continue
            seen_global.add(domain)
            unique.append(entry)
        unique.sort(key=lambda e: e["domain"])
        active[name] = unique

    merged_inactive = {e["domain"]: e for e in inactive}
    for entry in quarantined:
        merged_inactive[entry["domain"]] = entry
    # A domain must never appear in both an active file and inactive.json.
    inactive_out = sorted(
        (e for d, e in merged_inactive.items() if d not in seen_global),
        key=lambda e: e["domain"],
    )

    print(f"  active: {sum(len(v) for v in active.values())} | inactive: {len(inactive_out)} | duplicates dropped: {len(duplicates)}")
    report["normalise"] = {
        "shorteners": len(active["shorteners.json"]),
        "redirectors": len(active["redirectors.json"]),
        "tracking": len(active["tracking.json"]),
        "inactive": len(inactive_out),
        "duplicates_dropped": duplicates,
    }
    report["flat_mirror"] = report_flat

    # ------------------------------------------------------------------- write
    # The report is diagnostic output, not dataset state: always write it, so a
    # dry run can actually be inspected.
    save_json(args.report, report)

    if args.dry_run:
        print(f"\nDry run: no dataset changes written. Report: {rel(args.report)}")
    else:
        for name in ACTIVE_FILES:
            save_json(DATA / name, active[name])
        save_json(DATA / INACTIVE_FILE, inactive_out)

        if not args.no_flat:
            # Record what we deliberately did not adopt, so the maintainer sees
            # it in the file rather than only in one line of run log.
            notes = [f"# not adopted ({INACTIVE_FILE} has it): {d}" for d in flat_conflicts]
            notes += [f"# not adopted ({d})" for d in flat_aliases]
            write_lines(args.flat, FLAT_HEADER[:-1] + notes + [""], sorted(seen_global))

        # candidates.txt is an inbox: drop what we have decided on, keep the
        # rest (errors, or everything if Ollama was unavailable) for next run.
        if args.candidates.exists():
            decided = ({e["domain"] for e in accepted} | set(rejected)
                       | set(skipped_known) | {d for d, _, _ in review_queue})
            remaining = [format_candidate_line(d, pending[d])
                         for d in pending_domains if d not in decided]
            # Never silently drop a line we could not parse -- it is more likely
            # a typo the maintainer wants to fix than something to discard. A
            # previous run's "# unparseable:" line comes back as a comment, so
            # preserving comments is what keeps it alive across runs.
            remaining += [f"# unparseable: {line}" for line in unparseable]
            preserved = [ln for ln in raw_lines if ln.startswith("#")]
            write_lines(args.candidates, preserved + [""] if preserved else CANDIDATES_HEADER, remaining)
        # The review queue is what a human (or the workflow's PR) acts on. It is
        # rewritten whole each run: anything a maintainer moves back into
        # candidates.txt simply stops reappearing here.
        if review_queue or args.review.exists():
            existing: dict[str, str] = {}
            for ln in read_lines(args.review):
                parsed = parse_candidate_line(ln)
                if parsed:
                    existing[parsed[0]] = ln
            lines = []
            for domain, sources, why in sorted(review_queue):
                lines.append(f"# {why}")
                lines.append(format_candidate_line(domain, sources))
            # Keep entries queued by earlier runs that this run did not re-decide.
            carried = [ln for d, ln in sorted(existing.items())
                       if d not in {x for x, _, _ in review_queue} and d not in known
                       and d not in known_inactive]
            if carried:
                lines.append("")
                lines.extend(carried)
            write_lines(
                args.review,
                [
                    "# Candidates needing a human decision: the models disagreed, the",
                    "# corroboration was too thin, or liveness was inconclusive.",
                    "# To accept one, move its line into candidates.txt and delete it here.",
                    "",
                ],
                lines,
            )

        if rejected:
            previous = [
                ln for ln in read_lines(args.rejected) if ln and not ln.startswith("#")
            ]
            write_lines(
                args.rejected,
                [
                    "# Domains Ollama judged not to be shorteners/redirectors/trackers.",
                    "# Kept so they are not re-evaluated every week. Delete a line to retry it.",
                    "",
                ],
                sorted(set(previous) | set(rejected)),
            )
        written = ["data/*.json"]
        if review_queue:
            written.append(args.review.name)
        if not args.no_flat:
            written.append(args.flat.name)
        written.append(rel(args.report))
        print(f"\nWrote {', '.join(written)}")

    # ----------------------------------------------------------------- summary
    print("\n--- Summary ---")
    if not args.no_check:
        lv = report["liveness"]
        print(f"Checked {lv['checked']} | alive {lv['alive']} | quarantined {lv['quarantined']} | review {lv['review']}")
    print(f"Candidates: {len(pending_domains)} new | accepted {len(accepted)} | "
          f"rejected {len(rejected)} | needs review {len(review_queue)}")
    print(f"Dataset: {report['normalise']['shorteners']} shorteners, "
          f"{report['normalise']['redirectors']} redirectors, "
          f"{report['normalise']['tracking']} tracking, "
          f"{report['normalise']['inactive']} inactive")

    if quarantine_skipped:
        print("\nSafety cap tripped: nothing was quarantined. Review the report before rerunning.", file=sys.stderr)
        return EXIT_QUARANTINE_CAP
    return 0


if __name__ == "__main__":
    sys.exit(main())
